### ISSUE TITLE
Error after upgrading from 2.0.2 to 2.0.3

### ISSUE THREAD

**Issue by staskorz** [AllenFang/react-bootstrap-table#354]
The following error is received after upgrading from 2.0.2 to 2.0.3:

`Uncaught Error: Cannot find module 'events'`

Reverting back to 2.0.2 resolves the issue.

**Comment by AllenFang** [comment]
HI @staskorz , when the error messages be throw?

**Comment by staminaloops** [comment]
OK I spotted the problem. https://github.com/AllenFang/react-bootstrap-table/blob/master/src/store/TableDataStore.js

We are using event emitter but we didn't declare it as a dependency. Do we really need it? We could use other way of handling events without depending on event emitter

**Comment by AllenFang** [comment]
@staminaloops, I thinks it time to drop ```TableDataSet```, I dont want to keep support this feature anyway. I'll handle this.  Thanks your finding!

**Comment by staskorz** [comment]
Hi @AllenFang , it occurs on component load.

Thanks.

**Comment by AllenFang** [comment]
Released on ```v2.1.0```. I've removed the ```TableDataSet``` module from our project
